ScrumManager/ScrumManager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ScrumManager.DataBase;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;

namespace ScrumManager.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/


        public ActionResult Registro()
        {
            return View();
        }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AcercaDe()
        {
            return View();
        }

        public ActionResult Forms()
        {
            return View();
        }

        public ActionResult Tables()
        {
            return View();
        }

        //Login 
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Perfil()
        {
            return View();
        }

        public ActionResult Ingresar(String user, String pass)
        {
            /* Respuesta */
            String resultado = String.Empty;
            String mensaje = String.Empty;
            UserService login = new UserService();
            DataTable result = login.Login(user,pass);

            if (result.Rows.Count > 0)
            {
                resultado = "1";
                mensaje = "Ok";
            }
            else 
            {
                resultado = "0";
                mensaje = "Error";
            
            }
            return Json(new { resultado = resultado, msj = mensaje });
        }

        public ActionResult Registrar(String user, String pass, String correo, String nombre, String apellido, String direccion) {
            /* Respuesta */
            String resultado = String.Empty;
            String mensaje = String.Empty;
            UserService registro = new UserService();
            int bandera= registro.Registro(user, pass, correo, nombre, apellido, direccion);

            if (bandera==0)
            {
                resultado = "0";
                mensaje = "El usuario ya Existe...";
            }
            else
            {
                resultado = "1";
                mensaje = "Usuario creado Correctamente...";

            }
            return Json(new { resultado = resultado, msj = mensaje });
        }
    }
}

ScrumManager/ScrumManager/Controllers/TareaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScrumManager.Controllers
{
    public class TareaController : Controller
    {
        //
        // GET: /Tarea/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Estado_tareas()
        {
            return View();
        }

    }
}

ScrumManager/ScrumManager/Views/Home/AcercaDe.cshtml
@{
    ViewBag.Title = "AcercaDe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>
    GRUPO 1:
</h2>

<h3>
    INTEGRANTES:

</h3>

ScrumManager/ScrumManager/Views/Home/Forms.cshtml
@{
    ViewBag.Title = "Forms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Forms</h2>

ScrumManager/ScrumManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SCRUM Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1> SCRUM Manager</h1>


 
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <small>¿Que es SCRUM Manager?</small>
            </h1>
            <p>Es una herramienta que permite aplicar SCRUM a tus Proyectos</p>
            <p>Te permitira trabajar con tu equipo de trabajo de forma sencilla</p>
            <div class="row">
                <div class="col-lg-12">
                    <div class="alert alert-info alert-dismissable">

                        <i class="fa fa-info-circle"></i>  Crea y administra Proyectos <br />
                        <i class="fa fa-info-circle"></i>  Añade tareas <br />
                        <i class="fa fa-info-circle"></i>  Crea tu equipo de trabajo <br />


                    </div>
                </div>
            </div>
         </div>
     </div>
</div>

ScrumManager/ScrumManager/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"> Iniciar Sesión </h2>
            </div>
            <div class="panel-body">
                <form role="form">
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" id="txtUser" placeholder="Usuario" name="user" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtPass" placeholder="Constraseña" name="password" type="password" value="">
                        </div>
                        <input id="btnIngresar" type="button" class="btn btn-lg btn-success btn-block" value="Ingresar">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>




<div class="row">
    <div id="correcto" class="alert alert-success">
    </div>
</div>
<div class="row">
    <div id="error" class="alert alert-warning">
    </div>
</div>


<script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function () {
        $('#error').hide();
        $('#correcto').hide();
        $('#btnIngresar').click(function () {
            var user = $('#txtUser').val();
            var pass = $('#txtPass').val();
            if (user && (user != '') && pass && (pass != ''))
                verificar(user, pass);
        });
    });

    function verificar(user, pass) {
        $.ajax({
            type: "POST",
            url: "/Home/Ingresar",
            data: '{user: "' + user + '", pass : "' + pass + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (msg) {
                if (msg.resultado == "1") {
                     $('#correcto').html("<p> Sesion Iniciada: " + msg.msj + "</p>");
                     $('#correcto').show();
                     $('#error').hide();
                     var url = '@Url.Action("Perfil", "Home", new { usuario = "_id_"})';
                     window.location.href = url.replace("_id_", msg.msj);;

                } else {
                    $('#error').html("<p> Error al Iniciar: " + msg.msj + "</p>");
                    $('#error').show();
                    $('#correcto').hide();
                }
            },
            error: function (result) {
                alert("ERROR " + result.status + ' ' + result.statusText);
            }
        });

    };
</script>

ScrumManager/ScrumManager/Views/Home/Perfil.cshtml
@{
    ViewBag.Title = "Perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <h1>PEFIL DE USUARIO</h1>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <h3> Roberto Eduardo Caseros</h3>
        </div>
    </div>
</div>

<strong>
    USUARIO:
</strong>
<strong>
    EduardoC
</strong>
<br />
<strong>
    OCUPACIÓN:
</strong>
<strong>
    Desarrollador
</strong>
<br />
<strong>
    DOMICILIO:
</strong>
<strong>
    5 calle A 7 - 23 zona 4 de Mixco
</strong>
<br />
<strong>
    CORREO ELECTRONICO:
</strong>
<strong>
    eduard.caseros@gmail.com
</strong>
<br />

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">

            <i class="fa fa-info-circle"></i>  <strong> Proyectos en Curso</strong>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">    
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-right">
                        <h3>Colaboradores:</h3>
                    </div>
                </div>
            </div>
                <div class="panel-footer">
                    <span class="pull-left">
                        <select name="colaboradores">
                            <option value="user1">CarlogG</option>
                            <option value="user2">LeinderC</option>
                            <option value="user3">RandyN</option>
                            <option value="user4">DanielAlvizures</option>
                        </select>
                    </span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <br />
                    <br />
                    <div class="clearfix">
                        <div class="row">
                            <input id="btnCreateGroup" type="button" class="btn btn-lg btn-success btn-block" value="Crear Grupo">
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-right">
                        <h3>TuBanca.com</h3>
                        <div>Banca Virtual </div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Proyecto</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-left">
                        <h3>Batres.com</h3>
                        <div> Venta de medicamento en linea</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Proyecto</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    
</div>
<fieldset>
    @section Menu{
        <li>@Html.ActionLink("Estado Tareas", "Estado_tareas", "Tarea")</li>
    }
</fieldset>

<script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $('#tareas').click(function () {
            
        });
    });
</script>

ScrumManager/ScrumManager/Views/Home/Registro.cshtml
@{
    ViewBag.Title = "Registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registro</h2>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"> Registrar Usuario </h2>
            </div>
            <div class="panel-body">
                <form role="form">
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" id="txtUser" placeholder="Usuario" name="user" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtPass" placeholder="Constraseña" name="password" type="password" value="">
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtCorreo" placeholder="Correo" name="correo" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtNombre" placeholder="Nombre" name="nombre" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtApellido" placeholder="Apellido" name="Apellido" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtDireccion" placeholder="Direccion" name="Direccion" type="text" autofocus>
                        </div>
                        <input id="btnRegistrar" type="button" class="btn btn-lg btn-success btn-block" value="Registrar">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>




<div class="row">
    <div id="correcto" class="alert alert-success">
    </div>
</div>
<div class="row">
    <div id="error" class="alert alert-warning">
    </div>
</div>


<script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $('#error').hide();
        $('#correcto').hide();
        $('#btnRegistrar').click(function () {
            var user = $('#txtUser').val();
            var pass = $('#txtPass').val();
            var correo = $('#txtCorreo').val();
            var nombre = $('#txtNombre').val();
            var apellido = $('#txtApellido').val();
            var direccion = $('#txtDireccion').val();
            if (user && (user != '') && pass && (pass != '') && correo && (correo != '') && nombre && (nombre != '') && apellido && (apellido != '') && direccion && (direccion != ''))
                Registrar(user, pass, correo, nombre, apellido, direccion);
        });
    });

    function Registrar(user, pass, correo, nombre, apellido, direccion) {
        $.ajax({
            type: "POST",
            url: "/Home/Registrar",
            data: '{user: "' + user + '", pass : "' + pass +'", correo: "'+ correo + '", nombre: "'+ nombre + '", apellido: "'+ apellido + '", direccion: "'+direccion+ '"}',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (msg) {
                if (msg.resultado == "1") {
                     $('#correcto').html("<p>" + msg.msj + "</p>");
                     $('#correcto').show();
                     $('#error').hide();
                } else {
                    $('#error').html("<p>" + msg.msj + "</p>");
                    $('#error').show();
                    $('#correcto').hide();
                }
            },
            error: function (result) {
                alert("ERROR " + result.status + ' ' + result.statusText);
            }
        });

    };
</script>

ScrumManager/ScrumManager/Views/Home/Tables.cshtml
@{
    ViewBag.Title = "Tables";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tables</h2>

ScrumManager/ScrumManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>


<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Scrum Manager</title>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
    <!-- Bootstrap Core CSS -->
    <link href="../Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="../Content/css/sb-admin.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="../Content/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="../Content/css/plugins/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="../Content/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css">

</head>
        
<body>

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="Index">Scrum Manager</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                        
                        @Html.ActionLink("Login", "Login", "Home") 
                        @Html.ActionLink("Registrarse", "Registro", "Home")
                        
                    <!-- /.dropdownr -->
                </li>
                <!-- /.dropdown -->
            </ul>
            
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    @RenderSection("Menu", required: false)
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
            <!-- /.container-fluid -->
            @RenderBody()

        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="js/plugins/morris/raphael.min.js"></script>
    <script src="js/plugins/morris/morris.min.js"></script>
    <script src="js/plugins/morris/morris-data.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

ScrumManager/ScrumManager/Views/Tarea/Estado_tareas.cshtml
@{
    ViewBag.Title = "Estado_tareas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <h1>ESTADO DE TAREAS</h1>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <h3> Tareas en Curso</h3>
        </div>
    </div>
</div>

<!-- /.row -->
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-right">
                        <h3>Creacion del Login</h3>
                        <div>completado </div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Codigo</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-left">
                        <h3>Registro de usuarios</h3>
                        <div> completado</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Codigo</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>


    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-left">
                        <h3>Creacion del Script de Base de datos</h3>
                        <div>completado</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Codigo</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>


    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-left">
                        <h3>Conexion a Base de Datos</h3>
                        <div>En proceso</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Codigo</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-9 text-left">
                        <h3>Apariencia de Paginas Web</h3>
                        <div>pendiente</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Cosigo</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>    


</div>


<script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $('#btnCreateGroup').click(function () {
            console.log('clic al boton crear grupo');
        });
    });
</script>